import simplesbml
# model = simplesbml.SbmlModel()
# model.addCompartment(1e-14, comp_id='comp')
# model.addSpecies('E', 5e-21, comp='comp')
# model.addSpecies('S', 1e-20, comp='comp')
# model.addSpecies('P', 0.0, comp='comp')
# model.addSpecies('ES', 0.0, comp='comp')
# model.addParameter('koff', 0.2)
# model.addParameter('kon', 1000000.0)
# model.addParameter('kcat', 0.1)
# model.addReaction(['E', 'S'], ['ES'], 'comp*(kon*E*S-koff*ES)', rxn_id='veq')
# model.addReaction(['ES'], ['E', 'P'], 'comp*kcat*ES', rxn_id='vcat')
# code = simplesbml.writeCodeFromString(model.toSBML())
# print(code)
