@startuml

MatchResultCollection o-- MatchResult

'TimeSeries *-- SteadyState

class MatchResultCollection {
    +_match_result_dict : dict of variable_str to MarchResult
    +add_match_result(variable, match_result) : void
    +get_match_result(variable) : MatchResult

}

class MatchResult {

}

@enduml