@startuml

MatchResultCollection o-- MatchResult

'TimeSeries *-- SteadyState

class MatchResultCollection {
    +_match_result_dict : dict of variable_str to MarchResult
    +variables() :  numpy.ndarray
    +match_results() : numpy.ndarray
    +size() : int

    +add_match_result(variable, match_result) : void
    +get_match_result(variable) : MatchResult
}

class MatchResult {
    +_original_ts : TimeSeries
    +_revised_ts : TimeSeries
    +original_ts() : TimeSeries
    +revised_ts() : TimeSeries
}

@enduml