@startuml
class viper_dynamic {
    ~get_steady_state_time(time_series_a)
    ~get_steady_state_concentration(time_series_a)
    +is_match_steady_state(time_series_a, time_series_b, tolerance)
    +steady_state_greater_range(time_series_a, time_series_b, low, high)
}

note right of viper_dynamic::is_match_steady_state
  checks whether the steady-state of species A matches the steady-state of
  species B.

  tolerance indicates the relative error of fitting the steady-states.
end note

note right of viper_dynamic::steady_state_greater_range
  checks whether the steady state-concentration of species A is [low, high]
  times greater than the steady-state concentration of species B.

  low and high indicates the range of multiplication
end note

@enduml