@startuml
package SBviper {
    package ViperStatic
    package ViperDynamic
    package ViperHelpers
}

note right of ViperStatic {
    A static analyzer for sbml models.
    It parses the model and uses libsbml
    for conducting a bunch of checks such
    as checking for uninitialized parameters.

}

note bottom of ViperDynamic {
    These tests are user defined
    for a specific model. Like the
    steady-state concentration of
    species A should be 10 times
    larger than the steady-state
    concentration of species B.

}

note top of ViperHelpers {
    These are helper functions developed for
    implementing the static tester and dynamic
    tester. User can use functions from this
    library to develop their own tests. Each
    helper method will return helpful information
    such as a list of uninitialized libsbml parameter
    object.

}

note top of not_sure_yet {
    These are tests that require simulation
    and are valid for every model.

}
@enduml