@startuml

TimeSeriesCollection o-- TimeSeries

'TimeSeries *-- SteadyState

class TimeSeriesCollection {
    +time_series_dict : dict of species_str to TimeSeries object
    +variables() : numpy.ndarray
    +time_series() : numpy.ndarray
    +size() : int
    +add_time_series(variable, time_series) : void
    +get_time_series(variable) : TimeSeries
}

class TimeSeries {
    +variable : string
    +time_points : numpy.ndarray
    +variable() : string
    +time_points() : ndarray
    +values : numpy.ndarray
    +values() : list
    +size() : int
    +get_value_at_time(int time_point) : numpy.float64
    +replace_values_at(list time_points, list new_values) : void
}

note left of TimeSeriesCollection::get_time_series {
    returns the TimeSeries object of the input specie
}

note right of TimeSeries::time {
    len(time) = number_of_points
    time[0] = time_start
    time[len(time) - 1] = time_end
}

@enduml